config/routes.rb
Rails.application.routes.draw do
  resources :invents
  root 'simple_calendar#index'

end

app/models/invent.rb
class Invent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invents_controller.rb
class InventsController < ApplicationController
  before_action :set_invent, only: [:show, :edit, :update, :destroy]

  # GET /invents
  # GET /invents.json
  def index
    @invents = Invent.all
  end

  # GET /invents/1
  # GET /invents/1.json
  def show
  end

  # GET /invents/new
  def new
    @invent = Invent.new
  end

  # GET /invents/1/edit
  def edit
  end

  # POST /invents
  # POST /invents.json
  def create
    @invent = Invent.new(invent_params)

    respond_to do |format|
      if @invent.save
        format.html { redirect_to @invent, notice: 'Invent was successfully created.' }
        format.json { render :show, status: :created, location: @invent }
      else
        format.html { render :new }
        format.json { render json: @invent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invents/1
  # PATCH/PUT /invents/1.json
  def update
    respond_to do |format|
      if @invent.update(invent_params)
        format.html { redirect_to @invent, notice: 'Invent was successfully updated.' }
        format.json { render :show, status: :ok, location: @invent }
      else
        format.html { render :edit }
        format.json { render json: @invent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invents/1
  # DELETE /invents/1.json
  def destroy
    @invent.destroy
    respond_to do |format|
      format.html { redirect_to invents_url, notice: 'Invent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invent
      @invent = Invent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invent_params
      params.require(:invent).permit(:name, :title, :date,:link)
    end
end

app/controllers/simple_calendar_controller.rb
class SimpleCalendarController < ApplicationController
  def index
    @invents = Invent.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/invents_helper.rb
module InventsHelper
end

app/helpers/simple_calendar_helper.rb
module SimpleCalendarHelper
end

app/views/invents/_form.html.erb
<%= form_for(@invent) do |f| %>
  <% if @invent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invent.errors.count, "error") %> prohibited this invent from being saved:</h2>

      <ul>
      <% @invent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
    <div class="field">
      <%= f.label :link %><br>
      <%= f.text_field :link %>
    </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invents/edit.html.erb
<h1>Editing Invent</h1>

<%= render 'form' %>

<%= link_to 'Show', @invent %> |
<%= link_to 'Back', invents_path %>

app/views/invents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invents.each do |invent| %>
      <tr>
        <td><%= invent.name %></td>
        <td><%= invent.title %></td>
        <td><%= invent.date %></td>
        <td><%= link_to 'Show', invent %></td>
        <td><%= link_to 'Edit', edit_invent_path(invent) %></td>
        <td><%= link_to 'Destroy', invent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invent', new_invent_path %>

app/views/invents/new.html.erb
<h1>New Invent</h1>

<%= render 'form' %>

<%= link_to 'Back', invents_path %>

app/views/invents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invent.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @invent.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invent.date %>
</p>

<%= link_to 'Edit', edit_invent_path(@invent) %> |
<%= link_to 'Back', invents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<%= stylesheet_link_tag "simple_calendar.scss" %>

<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/index.html.erb
<% date_begin = 1 %>
<%= month_calendar do |date| %>
    <% day=(date.to_s.delete'-').to_i%100 %>
    <% if day == date_begin%>
        <%= day %>
        <% @invents.each do |invent| %>
            <% if invent.date == date%>
               <br><%= link_to invent.title ,"#{invent.link}" %>
            <% end %>
        <%end%>
        <% date_begin = date_begin+1%>
    <%end%>

<% end %>

<%= link_to :"Create new Event",new_invent_path%>